package com.serverless;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Bookshop-Orders")
@DynamoDBDocument
public class ordermodel {
    private String id;
    private String bookId;
    private Integer quantity;
    private String orderDate;
    private String name;
    private String contact;
    private String shippingAddress;
    private Float total;
    private String status;


    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "bookId")
    public String getBookId() {
        return bookId;
    }

    @DynamoDBAttribute(attributeName = "quantity")
    public Integer getQuantity() {
        return quantity;
    }

    @DynamoDBAttribute(attributeName = "orderDate")
    public String getOrderDate() {
        return orderDate;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    @DynamoDBAttribute(attributeName = "contact")
    public String getContact() {
        return contact;
    }

    @DynamoDBAttribute(attributeName = "shippingAddress")
    public String getShippingAddress() {
        return shippingAddress;
    }

    @DynamoDBAttribute(attributeName = "total")
    public Float getTotal() {
        return total;
    }

    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return status;
    }


    public void setId(String id) {
        this.id = id;
    }

    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }

    public void setTotal(Float total) {
        this.total = total;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
